# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92de04448b90170a47d86bf7c1e7f5d0d4a6735657dccb58dbff973e16e8c2310214c4169ffd052f62cddcfc42a377ca8b5ef6a96d35ac78fea668e3786cdaf0

test:
  secret_key_base: c63c5d73089eb78f4d70965620d669157730bbf3a8913448726cdf16552be2e580d1b9eacd125f5d0dab0ee131d0d0e98dc0dd78d0a1ee4d0725fecb49ea3bfb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
